### ISSUE TITLE
[BUG-UI/DEVELOPMENT] no user flow for `query` inside `similarity` search

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4417] opened 2023-12-18 10:03 UTC
**Describe the bug**
I am not sure if this cannot be  implemented or we don't want to support but currently there is no warning/explanation as to why normal queries are not working during similarity search.

**To Reproduce**
1. Go to a vector dataset
2. Click on most/least-similar
3. Try to query as well.
4. See NO error

**Expected behavior**
I would expect to filter the current records or to get a warning about not supporting this.

**Screenshots**
![image](https://github.com/argilla-io/argilla/assets/25269220/d42a2ac2-a4a1-4692-878d-638c0ad0ca29)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.2o
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.20

**Additional context**
N.A.

**Comment by nataliaElv** [comment] 2024-02-06 10:25
Closing as a duplicate of https://github.com/argilla-io/argilla/issues/4387

**Closed as completed by nataliaElv** 2024-02-06 10:25 UTC
Labels: type: bug, status: question, area: ui, team: frontend
