### ISSUE TITLE
[FEATURE] Add `ConversationField` for conversation support

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4483] opened 2024-01-11 15:46 UTC
**Is your feature request related to a problem? Please describe.**
Full [conversation support](https://github.com/argilla-io/argilla/issues/3338) is complex but we might hot-fix something using templating based on [an implementation](https://github.com/argilla-io/distilabel/pull/203) of @alvarobartt in distilabel.

**Describe the solution you'd like**
I would like to automatically format a `openai`-formatted conversation dict into a nice markdown render.

**Describe alternatives you've considered**
N.A.

**Additional context**
@dvsrepo I believe you meant to do this but had not gotter around to yet. Feel free to add some context.

**Comment by davidberenstein1957** [comment] 2024-01-11 15:47
This might be relevant for the https://github.com/argilla-io/argilla/issues/3735 implementation of Jonny Tran too.

**Comment by nataliaElv** [comment] 2024-02-22 13:54
Closing this one as a duplicate of #3338

**Closed as completed by nataliaElv** 2024-02-22 13:54 UTC
Labels: type: enhancement, area: ui, language: python
