### ISSUE TITLE
[BUG-python/deployment] Potential issue with sorting with question name and metadata property name being the same

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#4377] opened 2023-12-05 11:16 UTC
This needs reproduction from someone else but I have created a dataset where there's a question name (`score-chosen`) being the same as a metadata property and the sort functionality by the `score-chosen` metadata property seems to stop working.

1. I have checked the payloads and the backend seems to send an unordered list of records.
With name clash:
https://dvilasuero-ultrafeedback-curator.hf.space/dataset/1cf998cf-aebc-434a-9dd4-b883c3a7fb14/annotation-mode?_page=1&_status=pending&_sort=suggestion.score-chosen.score.desc

(test with sorting by metadata score-chosen)

2. I have created a new dataset changing the name of the metadata property to score and it seems to work well.

No name clash: https://dvilasuero-ultrafeedback-curator.hf.space/dataset/f1451716-d321-4fbd-b679-0f985cb70858/annotation-mode?_page=1&_status=pending&_sort=metadata.score.asc

This might or might not be the root cause but worth checking what's going on

**Comment by jfcalvo** [comment] 2023-12-14 11:14
I have been reproducing it locally with the following dataset (notice that I have a `rating-question` question and a metadata property using the same name):

```python
import argilla as rg

dataset = rg.FeedbackDataset(
  fields=[rg.TextField(name="text")],
  questions=[
    rg.RatingQuestion(name="rating-question", values=[1, 2, 3, 4]),
    rg.TextQuestion(name="text-question"),
    rg.LabelQuestion(name="label-question", labels=["one", "two"]),
    rg.MultiLabelQuestion(name="multi-label-question", labels=["one", "two", "three"]),
    rg.RankingQuestion(name="ranking-question", values=["ranking-1", "ranking-2", "ranking-3"]),
  ],
  metadata_properties=[
    rg.IntegerMetadataProperty(name="rating-question"),
  ],
)

dataset.add_records(
  records=[
    rg.FeedbackRecord(
      fields={"text": "record-1"},
      suggestions=[
        {"question_name": "rating-question", "value": 1},
        {"question_name": "text-question", "value": "suggestion-1",}
      ],
      metadata={
        "rating-question": 99,
      },
    ),
    rg.FeedbackRecord(
      fields={"text": "record-2"},
      suggestions=[
        {"question_name": "label-question", "value": "one"},
        {"question_name": "multi-label-question", "value": ["one", "two"]},
        {
          "question_name": "ranking-question",
          "value": [
            {"rank": 1, "value": "ranking-1"},
            {"rank": 2, "value": "ranking-2"},
            {"rank": 3, "value": "ranking-3"}
          ]
        }
      ],
      metadata={
        "rating-question": 66,
      },
    ),
  ],
)

dataset.push_to_argilla(name="test-dataset")
```

The problem that I have found is that even if you select in the UI to sort by metadata property the scope of the sort is using `suggestion` instead of `metadata` in the request.

This is the body of the search request even after select the sort by metadata property:

```
{
   "query":{
      
   },
   "sort":[
      {
         "scope":{
            "entity":"suggestion",
            "question":"rating-question",
            "property":"score"
         },
         "order":"asc"
      }
   ]
}
```

And it matches with your url @dvsrepo sorting by suggestion instead of metadata property. I will take a look with @damianpumar

**Comment by damianpumar** [comment] 2023-12-14 16:48
> I have been reproducing it locally with the following dataset (notice that I have a `rating-question` question and a metadata property using the same name):
> 
> 
> 
> ```python
> 
> import argilla as rg
> 
> 
> 
> dataset = rg.FeedbackDataset(
> 
>   fields=[rg.TextField(name="text")],
> 
>   questions=[
> 
>     rg.RatingQuestion(name="rating-question", values=[1, 2, 3, 4]),
> 
>     rg.TextQuestion(name="text-question"),
> 
>     rg.LabelQuestion(name="label-question", labels=["one", "two"]),
> 
>     rg.MultiLabelQuestion(name="multi-label-question", labels=["one", "two", "three"]),
> 
>     rg.RankingQuestion(name="ranking-question", values=["ranking-1", "ranking-2", "ranking-3"]),
> 
>   ],
> 
>   metadata_properties=[
> 
>     rg.IntegerMetadataProperty(name="rating-question"),
> 
>   ],
> 
> )
> 
> 
> 
> dataset.add_records(
> 
>   records=[
> 
>     rg.FeedbackRecord(
> 
>       fields={"text": "record-1"},
> 
>       suggestions=[
> 
>         {"question_name": "rating-question", "value": 1},
> 
>         {"question_name": "text-question", "value": "suggestion-1",}
> 
>       ],
> 
>       metadata={
> 
>         "rating-question": 99,
> 
>       },
> 
>     ),
> 
>     rg.FeedbackRecord(
> 
>       fields={"text": "record-2"},
> 
>       suggestions=[
> 
>         {"question_name": "label-question", "value": "one"},
> 
>         {"question_name": "multi-label-question", "value": ["one", "two"]},
> 
>         {
> 
>           "question_name": "ranking-question",
> 
>           "value": [
> 
>             {"rank": 1, "value": "ranking-1"},
> 
>             {"rank": 2, "value": "ranking-2"},
> 
>             {"rank": 3, "value": "ranking-3"}
> 
>           ]
> 
>         }
> 
>       ],
> 
>       metadata={
> 
>         "rating-question": 66,
> 
>       },
> 
>     ),
> 
>   ],
> 
> )
> 
> 
> 
> dataset.push_to_argilla(name="test-dataset")
> 
> ```
> 
> 
> 
> The problem that I have found is that even if you select in the UI to sort by metadata property the scope of the sort is using `suggestion` instead of `metadata` in the request.
> 
> 
> 
> This is the body of the search request even after select the sort by metadata property:
> 
> 
> 
> ```
> 
> {
> 
>    "query":{
> 
>       
> 
>    },
> 
>    "sort":[
> 
>       {
> 
>          "scope":{
> 
>             "entity":"suggestion",
> 
>             "question":"rating-question",
> 
>             "property":"score"
> 
>          },
> 
>          "order":"asc"
> 
>       }
> 
>    ]
> 
> }
> 
> ```
> 
> 
> 
> And it matches with your url @dvsrepo sorting by suggestion instead of metadata property. I will take a look with @damianpumar 
> 
> 
> 
> 
> 
> 

It's already fixed in the PR related, the problem was we were selecting the elements by name, because we thought that it was unique. Now we are selecting by instance of categories using the name and the key related.

Thanks !

**Closed as completed** 2024-01-09 10:08 UTC
Labels: type: bug, status: help wanted, area: server, area: api, language: python, team: backend
